global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fluentbit"
    static_configs:
      - targets: ["fluentbit:2020"]
    metrics_path: /api/v1/metrics/prometheus
